name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Get time
        uses: nanzm/get-time-action@v1.1
        id: time
        with:
          format: "YYYYMMDDHH"

      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME

      - name: Build the prod image
        run: "docker build . --file Dockerfile --tag eapriala/docker-react-prod-${{ steps.time.outputs.time }}"

      - name: Generate Deployment Package
        run: zip -r deploy.zip *

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Learning_docker-react
          environment_name: Learningdockerreact-env
          version_label: "Learning_docker-react-${{ steps.time.outputs.time }}"
          region: eu-central-1
          deployment_package: deploy.zip
