name: Docker Image CI

on: [workflow_dispatch]

jobs:
  build_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the prod image
        run: docker build . --file Dockerfile --tag eapriala/docker-react-prod
